version: 2.1

commands:
  print_job_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
      
jobs:
  print_job_details:
    docker:
      - image: cimg/base:stable
    steps:
      - print_job_id
  
workflows:
  print_job_details-workflow:
    jobs:
      - print_job_details
