version: 2.1

jobs:
  save_hello_world_output:
    working_directory: ~/circleci-learn
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create and store output.txt"
          command: echo "Hello, World!"" > ~/circleci-learn/output.txt
      - persist_to_workspace:
          root: .
          paths:
            - ~/circleci-learn/*
  print_output_from_workspace:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Print output.txt's content"
          command: cat ~/circleci-learn/output.txt
      - attach_workspace:
          at: ~/circleci-learn
  
workflows:
  save_hello_world_output-workflow:
    jobs:
      - save_hello_world_output
      - print_output_from_workspace:
          requires:
            - save_hello_world_output