version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create and store output.txt"
          command: echo "Hello, World!"" > output.txt
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - /tmp/dir/output.txt
  print_output_from_workspace:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Print output.txt's content"
          command: cat /tmp/dir/output.txt
      - attach_workspace:
          at: tmp/dir
  
workflows:
  save_hello_world_output-workflow:
    jobs:
      - save_hello_world_output
      - print_output_from_workspace:
          requires:
            - save_hello_world_output