version: 2.1

commands:
  print_job_id:
    steps:
      - run: echo ${CIRCLEWORKFLOW_ID}
      - run:
          name: failure rollback
          command: echo pipeline failed due to unkown error.
          when: on_fail        
      
jobs:
  print_job_details:
    docker:
      - image: cimg/base:stable
    steps:
      - print_job_id
  
workflows:
  print_job_details-workflow:
    jobs:
      - print_job_details
